/*CRIAR TABELA */
CREATE TABLE TABELA_DE_VENDEDORES
( MATRICULA varchar(5),
NOME varchar(100),
PERCENTUAL_COMISSAO float,
DATA_ADMISSAO date,
DE_FERIAS bit);

/*INSERIR DADOS NA TABELA*/
INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00233', 'João Geraldo da Fonseca', 0.10);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
 ('00235','Márcio Almeida Silva',0.08);
 
 INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00236','Cláudia Morais',0.08);

/*MODIFICANDO A TABELA DE VENDEDORES*/
INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00235','Márcio Almeida Silva','2014-08-15',0.08,0);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00236','Cláudia Morais','2013-09-17',0.08,1);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00237','Roberta Martins','2017-03-18',0.11,1);


select * from tabela_de_vendedores;

/*ATUALIZAR INFORMAÇÃO DENTRO DA TABELA*/
UPDATE TABELA_DE_VENDEDORES SET PERCENTUAL_COMISSAO = 0.11
WHERE MATRICULA = '00236';

UPDATE TABELA_DE_VENDEDORES SET NOME = 'José Geraldo da Fonseca Junior'
WHERE MATRICULA = '00233';

UPDATE TABELA_DE_VENDEDORES SET PERCENTUAL_COMISSAO = 0.07
WHERE MATRICULA = '00233';

/* APAGAR REGISTROS*/
DELETE FROM TABELA_DE_VENDEDORES WHERE MATRICULA = '00233'; 

/*INSERIR CHAVE PRIMÁRIA*/
ALTER TABLE tabela_de_vendedores ADD PRIMARY KEY(matricula);

/*VERIFICANDO DADOS CADASTRAIS*/
SELECT * FROM TABELA_DE_VENDEDORES WHERE NOME = 'Claudia Morais';

/*CONSULTAO  QUAIS VENDEDORES QUE TEM COMISSÃO ACIMA DE 10%*/
SELECT * FROM TABELA_DE_VENDEDORES;
SELECT * FROM TABELA_DE_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10;

/* os vendedores que foram admitidos da empresa a partir de 2016*/
select * from tabela_de_vendedores where year(DATA_ADMISSAO)>=2016;

/*os vendedores que estão de férias e que foram admitidos antes de 2016.*/
select * from tabela_de_vendedores where year(DATA_ADMISSAO)<2016 and DE_FERIAS=1;
