USE sucos;
/*CRIANO TABELA*/
CREATE TABLE tbProduto (
    PRODUTO VARCHAR(20),
    NOME VARCHAR(150),
    EMBALAGEM VARCHAR(50),
    TAMANHO VARCHAR(50),
    SABOR VARCHAR(50),
    PRECO_LISTA FLOAT
);
/*INSERINDO DADOS DA TABELA*/
INSERT INTO tbproduto
(PRODUTO,NOME,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES
('1040107', 'Light - 350 ml - Melância','Lata', '350 ml', 'Melância', 4.56);

/*CRIANDO CHAVE PRIMÁRIA*/
ALTER TABLE tbproduto ADD primary key(PRODUTO);

USE sucos;

INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES (
'1037797', 'Clean - 2 Litros - Laranja','PET', '2 Litros', 'Laranja', 16.01);

INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES (
'1000889', 'Sabor da Montanha - 700 ml - Uva','Garrafa', '700 ml', 'Uva', 6.31);

INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES (
'1004327', 'Videira do Campo - 1,5 Litros - Melância','PET', '1,5 Litros', 'Melância', 19.51);

USE sucos;

INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES(
'544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20);

INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES(
'1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

/*ATUALIZAR DADOS DA TABELA*/
UPDATE tbproduto SET EMBALAGEM = 'Lata', PRECO_LISTA = 2.46
WHERE PRODUTO = '544931';

UPDATE tbproduto SET EMBALAGEM = 'Garrafa'
WHERE PRODUTO = '1078680';

/*EXCLUIR REGISTRO DA TABELA*/
DELETE FROM tbproduto WHERE PRODUTO = '1078680';

/*ATUALIZAR DADOS DA TABELA*/
UPDATE tbproduto SET EMBALAGEM = 'Garrafa'
WHERE PRODUTO = '1078680';

SELECT * FROM tbproduto;